local RS = RingSlinger
local s = RS.Skins

//Default ammo for autogenerated characters
RS.defaultammo = 45

//Base cast
s["sonic"] = {
	ammo = 80,
	weapons = {RSWPN_SCATTER, RSWPN_NORMAL}
}
s["tails"] = {
	ammo = 75,
	weapons = {RSWPN_FLAME, RSWPN_STONE}
}
s["knuckles"] = {
	ammo = 150,
	weapons = {RSWPN_MACHINEGUN, RSWPN_SCATTER}
}
s["amy"] = {
	ammo = 65,
	weapons = {RSWPN_AUTOMATIC, RSWPN_ACCEL}
}
s["fang"] = {
	ammo = 70,
	weapons = {RSWPN_RAIL, RSWPN_GRENADE}
}
s["metalsonic"] = {
	ammo = 65,
	weapons = {RSWPN_EXPLOSION, RSWPN_SCATTER}
}

//Addon chars
s["espio"] = {
	ammo = 45,
	weapons = {RSWPN_ACCEL, RSWPN_GRENADE}
}
s["metalknuckles"] = {
	ammo = 40,
	weapons = {RSWPN_EXPLOSION, RSWPN_FLASH}
}
s["tailsdoll"] = {
	ammo = 30,
	weapons = {RSWPN_SEEKER, RSWPN_BOUNCE}
}
s["shadow"] = {
	ammo = 35,
	weapons = {RSWPN_SCATTER, RSWPN_ACCEL}
}
s["blaze"] = {
	ammo = 45,
	weapons = {RSWPN_FLAME, RSWPN_INFINITY}
}
s["marine"] = {
	ammo = 30,
	weapons = {RSWPN_SPLASH, RSWPN_RAIL}
}

s["dzombie"] = {
	ammo = 5,
	weapons = {RSWPN_ZMELEE, RSWPN_ZMELEE}
}
s["bob"] = {
	ammo = 55,
	weapons = {RSWPN_FLASH, RSWPN_NORMAL}
}

s["revenger"] = {
	ammo = 65,
	weapons = {RSWPN_SCATTER, RSWPN_MACHINEGUN}
}

s["chaoze"] = {
	ammo = 65,
	weapons = {RSWPN_NORMAL, RSWPN_FLAME}
}

s["peppino"] = {
	ammo = 110,
	weapons = {RSWPN_SCATTER, RSWPN_RAIL}
}

s["noise"] = {
	ammo = 70,
	weapons = {RSWPN_MACHINEGUN, RSWPN_AUTOSCATTER}
}

s["snick"] = {
	ammo = 75,
	weapons = {RSWPN_SCATTER, RSWPN_ACCEL}
}

s["fakepep"] = {
	ammo = 60,
	weapons = {RSWPN_ACCEL, RSWPN_INFINITY}
}