local ZE = RV_ZESCAPE

assert(ZE, "Zombie Escape not loaded! This file should be loaded AFTER Zombie Escape is loaded.")
local extrachars = {
    ["scarf"] = {
        normalspeed = 22 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT / 19,
        charability = CA_NONE,
        charability2 = CA2_NONE,
        startHealth = 125,
        maxHealth = 125,
        staminacost = 12,
        staminarun = 16*FRACUNIT,
        staminanormal = 27*FRACUNIT,
    },
    ["serpentine"] = {
        normalspeed = 22 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT/19,
        charability = CA_NONE,
        charability2 = CA2_NONE,
        startHealth = 120,
        maxHealth = 120,
        staminacost = 12,
        staminarun = 16*FRACUNIT,
        staminanormal = 24*FRACUNIT,
    },
    ["steve"] = {
        normalspeed = 22 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT / 19,
        charability = CA_NONE,
        charability2 = CA2_NONE,
        startHealth = 200,
        maxHealth = 325,
        staminacost = 5,
        staminarun = 16*FRACUNIT,
        staminanormal = 24*FRACUNIT,
    },
    ["oof"] = {
        normalspeed = 22 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT/19,
        charability = CA_NONE,
        charability2 = CA2_NONE,
        startHealth = 120,
        maxHealth = 120,
        staminacost = 12,
        staminarun = 16*FRACUNIT,
        staminanormal = 23*FRACUNIT,
    },
    ["peppino"] = {
        normalspeed = 22 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT/19,
        charability = CA_SWIM,
        charability2 = CA2_GUNSLINGER,
        startHealth = 110,
        maxHealth = 145,
        staminacost = 10,
        staminarun = 16*FRACUNIT,
        staminanormal = 25*FRACUNIT,
    },
    ["noise"] = {
        normalspeed = 22 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT/19,
        charability = CA_BOUNCE,
        charability2 = CA2_NONE,
        startHealth = 135,
        maxHealth = 135,
        staminacost = 9,
        staminarun = 16*FRACUNIT,
        staminanormal = 26*FRACUNIT,
        actionspd = 7 * FRACUNIT,
    },
    ["snick"] = {
        normalspeed = 22 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT/19,
        charability = CA_JUMPTHOK,
        charability2 = CA2_NONE,
        actionspd = 1 * FRACUNIT,
        startHealth = 70,
        maxHealth = 125,
        staminacost = 7,
        staminarun = 16*FRACUNIT,
        staminanormal = 25*FRACUNIT,
    },
    ["fakepep"] = {
        normalspeed = 22 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT/19,
        charability = CA_DOUBLEJUMP,
        charability2 = CA2_NONE,
        startHealth = 130,
        maxHealth = 150,
        staminacost = 12,
        staminarun = 16*FRACUNIT,
        staminanormal = 24*FRACUNIT,
    },
    ["motobugze"] = {
        normalspeed = 11 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT/19,
        charability = CA_DOUBLEJUMP,
        charability2 = CA2_NONE,
        startHealth = 1,
        maxHealth = 1,
        staminacost = 7,
        staminarun = 22*FRACUNIT,
        staminanormal = 24*FRACUNIT,
    },
    ["chaoze"] = {
        normalspeed = 10 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 17 * FRACUNIT/19,
        charability = CA_DOUBLEJUMP,
        charability2 = CA2_NONE,
        startHealth = 15,
        maxHealth = 50,
        staminacost = 12,
        staminarun = 16*FRACUNIT,
        staminanormal = 23*FRACUNIT,
    },
    ["xtreme"] = {
        normalspeed = 25 * FRACUNIT,
        runspeed = 100 * FRACUNIT,
        jumpfactor = 16 * FRACUNIT/19,
        charability = CA_NONE,
        charability2 = CA2_NONE,
        startHealth = 105,
        maxHealth = 145,
        staminacost = 13,
        staminarun = 16*FRACUNIT,
        staminanormal = 27*FRACUNIT,
    },
    ["milne"] = {
		normalspeed = 22 * FRACUNIT,
		runspeed = 100 * FRACUNIT,
		jumpfactor = 12 * FRACUNIT/10,
		charability = CA_NONE,
		charability2 = CA2_NONE,
		charflags = SF_NOJUMPSPIN|SF_NOSKID,
		startHealth = 75,
		maxHealth = 100,
		staminacost = 10,
		staminarun = 16*FRACUNIT,
		staminanormal = 25*FRACUNIT,
	},
}


table.insert(ZE.CharacterStats, extrachars)